Anvil1:
  type: evm-main
  chainUri: 'http://localhost:8545'
  chainId: 31337
  chainCurrencyName: 'ETH'
  chainCurrencySymbol: 'ETH'
  chainCurrencyDecimals: 18
  blockTime: 2
  paimaL2ContractAddress: '0x5FbDB2315678afecb367f032d93F642f64180aa3'
  
Mina:
  type: mina
  archiveConnectionString: "postgresql://postgres:postgres@localhost:5432/archive"
  paginationLimit: 1
  delay: 600
