# yaml-language-server: $schema=../config-json-schema.json

Anvil1:
  type: evm-main
  chainUri: 'http://localhost:8545'
  chainId: 31337
  chainCurrencyName: 'ETH'
  chainCurrencySymbol: 'ETH'
  chainCurrencyDecimals: 18
  blockTime: 2
  paimaL2ContractAddress: '0x5FbDB2315678afecb367f032d93F642f64180aa3'
  # funnelBlockGroupSize: 1
  funnelBlockGroupSize: 100

Anvil2:
  type: evm-other
  chainUri: 'http://localhost:8546'
  chainId: 31338
  chainCurrencyName: 'ETH'
  chainCurrencySymbol: 'ETH'
  chainCurrencyDecimals: 18
  blockTime: 2
  # funnelBlockGroupSize: 1
  funnelBlockGroupSize: 100
